# Generated by Django 4.2.4 on 2023-08-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseXP', '0002_alter_department_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='admin',
        ),
    ]
