# Generated by Django 4.2.4 on 2023-08-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleatrentalstation',
            name='rental_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rent.rentalstation'),
        ),
        migrations.AlterField(
            model_name='vehicleatrentalstation',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rent.vehicle'),
        ),
    ]
