# Generated by Django 4.2.4 on 2023-08-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_remove_rental_vehicle_remove_rentalstation_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleatrentalstation',
            name='rental_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.rentalstation'),
        ),
        migrations.AlterField(
            model_name='vehicleatrentalstation',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.vehicle'),
        ),
    ]
