# Generated by Django 4.2.4 on 2023-08-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_vehicleatrentalstation_rental_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleatrentalstation',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
