# Generated by Django 4.2.4 on 2023-08-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_vehicleatrentalstation_arrival_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleatrentalstation',
            name='rental_station',
        ),
        migrations.AddField(
            model_name='rentalstation',
            name='vehicle_at_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.vehicleatrentalstation'),
        ),
    ]
